# Generated by Django 5.2.6 on 2025-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_user.png', upload_to='profile_pics/'),
        ),
    ]
